### ISSUE TITLE
Incremental build often fails

### ISSUE THREAD

**Issue by Tridie2000** [LikeTheSalad/android-buddy#1] opened 2020-12-24 23:12 UTC
I am running into an issue where an incremental build fails and I have to do a clean build (which succeeds). I am running into this quite often. Did I mess something up during the installation or is this a limitation or bug of this plugin?

I am using the Aaper library so I am not using android-buddy directly.  

<img width="1588" alt="Schermafbeelding 2020-12-25 om 00 02 27" src="https://user-images.githubusercontent.com/24608795/103108149-46d53e00-4645-11eb-926b-4dd2119d7cf1.png">

**Comment by LikeTheSalad** [comment] 2021-01-04 06:53
Hi @Tridie2000 thanks for your feedback, I don't remember having issues with incremental builds and there isn't supposed to be anything extra to be done for it to work so I think you're fine in that sense. Though what you mention is strange for sure so I'd like to have a couple more details in order to take a deeper look at it, such as what's the Gradle version you're using, and also the Android Build plugin version as well, please.

Also, if possible, could you describe the steps to reproduce it? e.g. "adding an Aaper annotation to a method -> then changing the method's body -> then rebuilding -> error". Something like that would help a lot as well.

Thanks,
Cesar

**Comment by Tridie2000** [comment] 2021-01-06 10:14
Android Gradle Plugin: 4.1.1
Gradle: 6.5
Aaper: 1.0.1
Android Buddy Plugin: 0.8.4

I tried to reproduce and isolate the issue in a sample project but I haven't been able to reproduce it there. Android Buddy fails to transform when a method inside a viewModel changes from name, parameters or is removed completely. When I switch branches there is a high probability it will throw an error like this:

> Execution failed for task ':app:transformClassesWithAndroidBuddyForDebug'.
> logIn()V not declared by class com.tridie2000.myapp.presentation.viewModels.LoginViewModel

I assume this is because on branch A the logIn() method had no parameters and on branch B the logIn() method had some parameters.

**Comment by LikeTheSalad** [comment] 2021-01-06 10:46
Thanks for the detailed info! I've never tried switching branches in my tests before so I'm going to take a look at that case later on this week to check if I can reproduce it as well! 

Just one more thing though which I think it's important for me to understand it better, I noticed that you're mentioning this ViewModel method that is showing up in the error logs in a way that seems like the issue could be happening when such method's signature changes, I just want to make sure, is this method the one annotated with Aaper's EnsurePermissions annotation? Or is this method being called from a EnsurePermissions-annotated method elsewhere? - I'm asking because, by default Aaper only supports annotated methods in either Activities or Fragments, so I just want to make sure if it's the former case (you are annotating a ViewModel's method) then if that's the case you might have created your own Byte Buddy transformation for ViewModels?

**Comment by Tridie2000** [comment] 2021-01-06 13:04
No the logIn method is not annotated with EnsurePermissions, currently I only have one method inside a fragment annotated with EnsurePermissions. The logIn method doesn't get called from a method that is annotated with EnsurePermissions.

**Comment by LikeTheSalad** [comment] 2021-01-11 07:04
Hi @Tridie2000, I've been taking a look at it lately and, same as what it seemed to happen in your case with a new project, I couldn't reproduce it. However, I did notice some other errors related to newer versions of the android build plugin, so I took the opportunity to update a couple of dependencies and change the way of gathering the project dependencies during the android buddy libraries search process.

I would say give it a try to the new versions (you should upgrade both at the same time), for both Android Buddy (0.8.5) and Aaper (1.0.2), which have also newer versions of the android build plugin and Byte Buddy just in case the issue was on those, so hopefully that'll do. However, if you still keep on getting the same issue afterwards, I'd need a bit more of info on your project, especially in terms of whether you might be using other libraries that also do transform your code, I'm asking based on the fact that the issue cannot get reproduced in new projects, so the only thing left I can think of now would be some other transforming dependency you might have that clashes with Android Buddy.

Please let me know how it goes!

**Comment by Tridie2000** [comment] 2021-03-20 14:00
After the update the error message appears to have changed, it appears to be clashing with RxJava which I find weird. I tried reproducing it in a separate project but no matter what combination of dependencies I tried, I couldn't reproduce it there.

new error:
<img width="2313" alt="Schermafbeelding 2021-01-19 om 18 52 24" src="https://user-images.githubusercontent.com/24608795/111871909-d1031900-898c-11eb-8101-b838cd0a6b79.png">

**Comment by LikeTheSalad** [comment] 2021-03-22 19:14
I see, thanks for trying again. I'm going to try and contact Byte Buddy's creator on this, just to see if this rings a bell for him. It is strange that it only happens on one project though, just to confirm, the issue with this new version is happening the same way as with the previous one? meaning that it's not always reproducible and it happens mostly when some method signature changes after switching branches? -  Because if that's so then I'd need to confirm as well if the Android transformation API is getting some cached classes, which shouldn't be happening tbh.

Also, just by chance do you happen to know if there's any other library in this project that's also transforming your classes? - Just to discard a transforming clash case since it's not happening on other projects, I'm curious if it's a matter of combining this plugin with another one that also changes classes...

**Comment by Tridie2000** [comment] 2021-03-28 08:42
Can't say for sure if it's still happening when a method signature changes. After the update the only times the transformation failed was when I meant to type "Completable" and Android Studio autocompleted "CompletableEmitter", I would then delete the import, write the correct code, compile and run into a failed transformation. The image above is an example of such an error. 

I'm not sure if any of the libraries are transforming classes, I do know that the "Navigation Component" generates some classes. Apart from that I'm also using RxJava, RxAndroid, ViewPager, Timber, Retrofit, Firebase Auth & Firestore, Klaxon, kProgressHud

When I ran into these transformation issues I was in the process of refactoring the app from a spaghetti codebase into something maintainable, so I was moving things around, breaking everything and fixing things until it compiled again. Perhaps this also contributed to these transformation issues.

**Comment by LikeTheSalad** [comment] 2021-03-28 12:37
Got it, many thanks for that detailed info! let me check what can I do 👍

**Comment by LikeTheSalad** [comment] 2021-03-28 13:17
I asked about this in the Byte Buddy repo just to check if this is something seen before and/or if they can tell us roughly in what situations these types of issues can be thrown, so that I could review the Byte Buddy configs on Android Buddy just in case is needed. Thanks again for all the info you've provided on this and hopefully we'll be able to sort this out soon!

In the meantime, based on what you've mentioned about autocomplete and refactoring, I'd suggest you to do an `Invalidate caches and restart` in Android Studio via File -> Invalidate Caches / Restart -> Invalidate and Restart. Just to make sure that the big amount of code changes done for the refactoring aren't somehow affecting the cache of your project when you switch to the branch with the refactorings. Usually Android Studio gets some annoying issues that only get away after invalidating caches.

Anyway, only if you haven't tried it already. Hopefully at least that makes the issue go away while I figure out what's going on so that you don't get these annoying issues in the meantime.

**Comment by LikeTheSalad** [comment] 2021-04-02 16:25
Hi @Tridie2000 - I've spent the past couple of hours trying to reproduce this issue in different ways, by adding the dependencies you've mentioned within the same Gradle env and Android build version and also doing the CompletableEmitter autocomplete case and so far, renaming methods across branches and also transforming Java classes to Kotlin ones across branches as well and, unfortunately, I haven't been able of reproducing it.

If you take a look at the issue I opened in here: https://github.com/raphw/byte-buddy/issues/1034 it seems like this could be caused by an incremental issue as you suggested, though interestingly enough (something I didn't know until now), the incremental compilation for Kotlin isn't handled by Gradle's Java compilation but rather the Kotlin plugin so I was suggested to open up an issue in Kotlin in regards to this issue, but I wouldn't like to do so without having a stable way of reproducing it. So there's just a couple of things I'd like to mention you in overall regarding this. The most important thing would be that, I'm open and willing to help solving this issue anytime, though unfortunately there's not much I can do if I can't reproduce it, therefore if you'd like taking the time of setting up a sample project where you're able of reproducing it on-demand or at least in most of the cases, that'll help a lot. If that's not possible, then the only thing I could do for you would be recommending some actions on your project such as:
- Updating the Kotlin plugin/libraries to the latest version (based on the fact that it's this plugin the one that handles incremental compilation for Kotlin files).
- Updating Aaper and Android Buddy to their latest versions.
- Try and address the warnings that show up in the logs of your compilation (such as the ones mentioning deprecated tools being used and defining multiple versions of the same dependencies in the project).
- Removing the `.gradle` folder once after switching to your new branch (the one with the refactorings) in order to make sure nothing's cached from the old version of the project.
- Doing an Invalidate caches / Restart.
- Optionally doing a test where you remove Android Buddy from your project and see if no compilation (nor runtime) issues are raised even after following the same steps to reproduce it now.

I was thinking that maybe the amount of changes done for the refactoring are so many that possibly the incremental build can't keep up with switching branches, however, it is supposed that these incremental tools should be able to tell when to do a full compilation due to these cases, but again, since I'm not able of reproducing it, I wouldn't be able to tell what could be causing it. There's a couple of issues listed in a comment of mine in the Byte Buddy issue I provided before that are related to incremental compilation errors and seem quite similar to your issue, but are also quite old so most likely they should have been addressed by now I suppose, which is why I mentioned the option of updating the compilers.

I hope that after doing all of that, and once you don't need to keep on switching branches with the old version of the project prior to refactoring, you shouldn't see these kinds of issues anymore.

**Comment by Tridie2000** [comment] 2021-04-15 16:56
I haven't worked that much on the project since the major refactor so I can't say for sure that the issue has been resolved, but after the refactor Aaper and Android Buddy have been working flawlessly. I'll keep the Kotlin plugin, Aaper and Android Buddy up-to-date. If I run into this issue again and I'm able to reliably reproduce this in a sample project you'll be the first to know. 

I don't know what your policy is but I think this issue can be closed. If I - or some other future user - can reliably reproduce this inside a sample project it can always be reopened.

**Comment by LikeTheSalad** [comment] 2021-04-18 09:08
That's great news! Thanks for letting me know, I'm glad you haven't seen any further issues and yeah, I think we can close this then and should you find something similar please don't hesitate on re-opening this ticket 👍 

Regards,
Cesar

**Closed as completed by LikeTheSalad** 2021-04-18 09:08 UTC
